In [2]:
print("Environment is working")

Environment is working

In [3]:
!pip install nflreadpy

Collecting nflreadpy
  Downloading nflreadpy-0.1.5-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: requests>=2.28.0 in c:\users\owner\anaconda3\lib\site-packages (from nflreadpy) (2.32.5)
Collecting polars>=0.20.0 (from nflreadpy)
  Downloading polars-1.42.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=3.0.0 in c:\users\owner\anaconda3\lib\site-packages (from nflreadpy) (4.5.0)
Requirement already satisfied: tqdm>=4.64.0 in c:\users\owner\anaconda3\lib\site-packages (from nflreadpy) (4.67.1)
Requirement already satisfied: pydantic>=2.0.0 in c:\users\owner\anaconda3\lib\site-packages (from nflreadpy) (2.12.4)
Requirement already satisfied: pydantic-settings>=2.0.0 in c:\users\owner\anaconda3\lib\site-packages (from nflreadpy) (2.12.0)
Collecting polars-runtime-32==1.42.1 (from polars>=0.20.0->nflreadpy)
  Downloading polars_runtime_32-1.42.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\owner\anaconda3\lib\site-packages (from pydantic>=2.0.0->nflreadpy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\owner\anaconda3\lib\site-packages (from pydantic>=2.0.0->nflreadpy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\owner\anaconda3\lib\site-packages (from pydantic>=2.0.0->nflreadpy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\owner\anaconda3\lib\site-packages (from pydantic>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\owner\anaconda3\lib\site-packages (from pydantic-settings>=2.0.0->nflreadpy) (1.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.28.0->nflreadpy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.28.0->nflreadpy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.28.0->nflreadpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\owner\anaconda3\lib\site-packages (from requests>=2.28.0->nflreadpy) (2026.6.17)
Requirement already satisfied: colorama in c:\users\owner\anaconda3\lib\site-packages (from tqdm>=4.64.0->nflreadpy) (0.4.6)
Downloading nflreadpy-0.1.5-py3-none-any.whl (30 kB)
Downloading polars-1.42.1-py3-none-any.whl (837 kB)
   ---------------------------------------- 0.0/837.6 kB ? eta -:--:--
   ---------------------------------------- 837.6/837.6 kB 12.7 MB/s  0:00:00
Downloading polars_runtime_32-1.42.1-cp310-abi3-win_amd64.whl (52.7 MB)
   ---------------------------------------- 0.0/52.7 MB ? eta -:--:--
   ---- ----------------------------------- 6.0/52.7 MB 28.6 MB/s eta 0:00:02
   -------- ------------------------------- 11.5/52.7 MB 28.9 MB/s eta 0:00:02
   ------------- -------------------------- 17.8/52.7 MB 28.7 MB/s eta 0:00:02
   ----------------- ---------------------- 22.8/52.7 MB 29.2 MB/s eta 0:00:02
   ------------------- -------------------- 25.4/52.7 MB 24.6 MB/s eta 0:00:02
   ----------------------- ---------------- 30.4/52.7 MB 24.7 MB/s eta 0:00:01
   --------------------------- ------------ 36.7/52.7 MB 25.2 MB/s eta 0:00:01
   -------------------------------- ------- 43.3/52.7 MB 26.0 MB/s eta 0:00:01
   ------------------------------------ --- 48.8/52.7 MB 26.7 MB/s eta 0:00:01
   -------------------------------------- - 51.1/52.7 MB 24.6 MB/s eta 0:00:01
   ---------------------------------------  52.7/52.7 MB 24.3 MB/s eta 0:00:01
   ---------------------------------------- 52.7/52.7 MB 22.0 MB/s  0:00:02
Installing collected packages: polars-runtime-32, polars, nflreadpy

   ---------------------------------------- 0/3 [polars-runtime-32]
   ---------------------------------------- 0/3 [polars-runtime-32]
   ---------------------------------------- 0/3 [polars-runtime-32]
   ---------------------------------------- 0/3 [polars-runtime-32]
   ------------- -------------------------- 1/3 [polars]
   ------------- -------------------------- 1/3 [polars]
   ------------- -------------------------- 1/3 [polars]
   ------------- -------------------------- 1/3 [polars]
   ------------- -------------------------- 1/3 [polars]
   ------------- -------------------------- 1/3 [polars]
   ------------- -------------------------- 1/3 [polars]
   -------------------------- ------------- 2/3 [nflreadpy]
   ---------------------------------------- 3/3 [nflreadpy]

Successfully installed nflreadpy-0.1.5 polars-1.42.1 polars-runtime-32-1.42.1

In [4]:
import nflreadpy as nfl

combine_data = nfl.load_combine()
combine_df = combine_data.to_pandas()

combine_df.head()

,season,draft_year,draft_team,draft_round,draft_ovr,pfr_id,cfb_id,player_name,pos,school,ht,wt,forty,bench,vertical,broad_jump,cone,shuttle
0,2000,2000.0,New York Jets,1.0,13.0,AbraJo00,None,John Abraham,OLB,South Carolina,6-4,252.0,4.55,NaN,NaN,NaN,NaN,NaN
1,2000,2000.0,Seattle Seahawks,1.0,19.0,AlexSh00,shaun-alexander-1,Shaun Alexander,RB,Alabama,6-0,218.0,4.58,NaN,NaN,NaN,NaN,NaN
2,2000,2000.0,Kansas City Chiefs,6.0,188.0,AlfoDa20,None,Darnell Alford,OT,Boston Col.,6-4,334.0,5.56,23.0,25.0,94.0,8.48,4.98
3,2000,NaN,None,NaN,NaN,None,None,Kyle Allamon,TE,Texas Tech,6-2,253.0,4.97,NaN,29.0,104.0,7.29,4.49
4,2000,2000.0,Carolina Panthers,1.0,23.0,AndeRa21,None,Rashard Anderson,CB,Jackson State,6-2,206.0,4.55,NaN,34.0,123.0,7.18,4.15

In [6]:
combine_df['pos'].unique()

array(['OLB', 'RB', 'OT', 'TE', 'CB', 'K', 'P', 'S', 'OG', 'ILB', 'DE',
       'DT', 'QB', 'WR', 'C', 'FB', 'LS', 'DL', 'EDGE', 'LB', 'DB', 'OL',
       'G', 'SAF', 'CB/WR'], dtype=object)

In [7]:
my_positions = ['CB', 'S', 'WR']
filtered_combine = combine_df[combine_df['pos'].isin(my_positions)]

filtered_combine.shape

(2715, 18)

In [8]:
player_stats = nfl.load_player_stats(seasons=True)
stats_df = player_stats.to_pandas()

stats_df.head()

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,team,...,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr,game_id
0,0,None,None,None,None,None,1999,1,REG,ATL,...,0,NaN,0,0,0,0,0,0.0,0.0,None
1,00-0000003,A.al-Jabbar,Abdul-Karim al-Jabbar,RB,RB,https://static.www.nfl.com/image/private/f_aut...,1999,1,REG,MIA,...,0,NaN,0,0,0,0,0,12.7,13.7,None
2,00-0000007,R.Abdullah,Rabih Abdullah,RB,RB,https://static.www.nfl.com/image/private/f_aut...,1999,1,REG,TB,...,0,NaN,0,0,0,0,0,0.0,0.0,None
3,00-0000008,R.Abdullah,Rahim Abdullah,OLB,LB,https://static.www.nfl.com/image/private/f_aut...,1999,1,REG,CLE,...,0,NaN,0,0,0,0,0,0.0,0.0,None
4,00-0000017,D.Abraham,Donnie Abraham,CB,DB,https://static.www.nfl.com/image/private/f_aut...,1999,1,REG,TB,...,0,NaN,0,0,0,0,0,0.0,0.0,None

In [9]:
player_stats_offense = nfl.load_player_stats(seasons=True, stat_type='offense')
stats_offense_df = player_stats_offense.to_pandas()

stats_offense_df.columns

TypeError: load_player_stats() got an unexpected keyword argument 'stat_type'

In [10]:
help(nfl.load_player_stats)

Help on function load_player_stats in module nflreadpy.load_stats:

load_player_stats(
    seasons: int | list[int] | bool | None = None,
    summary_level: Literal['week', 'reg', 'post', 'reg+post'] = 'week'
) -> polars.dataframe.frame.DataFrame
    Load NFL player statistics.

    Args:
        seasons: Season(s) to load. If None, loads current season.
                If True, loads all available data.
                If int or list of ints, loads specified season(s).
        summary_level: Summary level ("week", "reg", "post", "reg+post").

    Returns:
        Polars DataFrame with player statistics.

    See Also:
        <https://nflreadr.nflverse.com/reference/load_player_stats.html>

    Data Dictionary:
        <https://nflreadr.nflverse.com/articles/dictionary_player_stats.html>

In [11]:
player_stats_all = nfl.load_player_stats(seasons=True, summary_level='reg')
stats_all_df = player_stats_all.to_pandas()

stats_all_df.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'season', 'season_type',
       'recent_team', 'games',
       ...
       'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att',
       'gwfg_missed', 'gwfg_blocked', 'gwfg_distance_list', 'fantasy_points',
       'fantasy_points_ppr'],
      dtype='object', length=113)

In [12]:
for col in stats_all_df.columns:
    print(col)

player_id
player_name
player_display_name
position
position_group
headshot_url
season
season_type
recent_team
games
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
racr
target_share
air_yards_share
wopr
special_teams_tds
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds
penalties
penalty_yards
punt_returns
punt_return_yards
kickoff_returns
kickoff_return_yards
fg_made
fg_att
fg_missed
fg_blocked
fg_long
fg_pct
fg_made_0_19
fg_made_20_29
fg_made_30_39
fg_made_40_49
fg_made_50_59
fg_made_60_
fg_missed_0_19
fg_missed_20_29
fg_missed_30_39
fg_missed_40_49
fg_missed_50_59
fg_missed_60_
fg_made_list
fg_missed_list
fg_blocked_list
fg_made_distance
fg_missed_distance
fg_blocked_distance
pat_made
pat_att
pat_missed
pat_blocked
pat_pct
gwfg_made
gwfg_att
gwfg_missed
gwfg_blocked
gwfg_distance_list
fantasy_points
fantasy_points_ppr

In [13]:
my_positions = ['CB', 'S', 'WR']

cols_to_keep = [
    'player_id', 'player_name', 'position', 'season', 'recent_team', 'games',
    'receptions', 'targets', 'receiving_yards', 'receiving_tds',
    'def_interceptions', 'def_pass_defended', 'def_tackles_solo',
    'def_sacks', 'def_interception_yards'
]

filtered_stats = stats_all_df[stats_all_df['position'].isin(my_positions)][cols_to_keep]

filtered_stats.shape

(10124, 15)

In [14]:
filtered_combine.to_csv('combine_data_cb_s_wr.csv', index=False)
filtered_stats.to_csv('player_season_stats.csv', index=False)

print("Both files saved successfully")

Both files saved successfully

In [15]:
import os
print(os.getcwd())

C:\Users\owner